window.RV=window.RV||{};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];RV.$=$;RV.$$=$$;RV.currentFolder=null;RV.currentView='library';
RV.applySkin=function(){const skin=RV.db.settings.skin||'red',s=RV.SKINS[skin]||RV.SKINS.red;document.documentElement.style.setProperty('--accent',s.accent);document.documentElement.style.setProperty('--accent2',s.accent2);$$('.skin').forEach(x=>x.classList.toggle('active',x.dataset.skin===skin));$('#endMode').value=RV.db.settings.endMode;const suffix=skin==='gray'?'grey':skin;[['brandIcon',`icons/icon-${suffix}-512.png`],['brandWordmark',`icons/logo-${suffix}.png`],['splashIcon',`icons/icon-${suffix}-512.png`],['splashWordmark',`icons/logo-${suffix}.png`]].forEach(([id,src])=>{const el=document.getElementById(id);if(el)el.src=src})};
RV.songRow=s=>`<div class="row sortableRow" data-kind="song" data-id="${s.id}"><button class="mini dragHandle" aria-label="Reordenar">☰</button><img class="thumb" src="${s.thumbnail}" alt=""><div class="rowMain songOpen" data-id="${s.id}"><div class="rowTitle">${RV.esc(s.title)}</div><div class="rowMeta">${RV.esc(s.artist||'Artista desconocido')}</div></div><div class="rowActions"><button class="mini favoriteBtn" data-id="${s.id}">${s.favorite?'★':'☆'}</button><button class="mini moveSongBtn" data-id="${s.id}">↗</button><button class="mini deleteSongBtn" data-id="${s.id}">🗑</button></div></div>`;
RV.render=function(){RV.applySkin();$('#settingsView').hidden=true;$('#libraryView').hidden=false;const inbox=RV.db.songs.filter(s=>!s.folderId).length;$('#inboxCount').textContent=inbox?`(${inbox})`:'';const q=$('#searchInput').value.trim().toLowerCase(),scope=RV.currentView==='inbox'?[]:(RV.currentFolder?RV.descendants(RV.currentFolder):RV.db.folders.map(f=>f.id));let folders=RV.currentView==='inbox'?[]:RV.db.folders.filter(f=>f.parentId===RV.currentFolder).sort((a,b)=>(a.order??0)-(b.order??0));let songs=RV.currentView==='inbox'?RV.db.songs.filter(s=>!s.folderId):RV.db.songs.filter(s=>s.folderId===RV.currentFolder);if(q){folders=RV.db.folders.filter(f=>(!RV.currentFolder||scope.includes(f.id))&&f.name.toLowerCase().includes(q));songs=RV.db.songs.filter(s=>(RV.currentView==='inbox'?!s.folderId:(!RV.currentFolder||scope.includes(s.folderId)))&&(`${s.title} ${s.artist||''}`).toLowerCase().includes(q))}$('#folderList').innerHTML=folders.length?folders.map(f=>`<div class="row sortableRow" data-kind="folder" data-id="${f.id}"><button class="mini dragHandle" aria-label="Reordenar">☰</button><div class="folderIcon">📁</div><div class="rowMain folderOpen" data-id="${f.id}"><div class="rowTitle">${RV.esc(f.name)}</div><div class="rowMeta">${RV.db.folders.filter(x=>x.parentId===f.id).length} carpetas · ${RV.db.songs.filter(x=>RV.descendants(f.id).includes(x.folderId)).length} canciones</div></div><div class="rowActions"><button class="mini renameFolderBtn" data-id="${f.id}">✎</button><button class="mini deleteFolderBtn" data-id="${f.id}">🗑</button></div></div>`).join(''):'<div class="empty">No hay carpetas aquí.</div>';$('#songList').innerHTML=songs.length?songs.sort((a,b)=>(a.order??0)-(b.order??0)).map(RV.songRow).join(''):'<div class="empty">No hay canciones aquí.</div>';$('#songCount').textContent=songs.length;RV.renderBreadcrumb();RV.populateDestinations();RV.bindDrag('#folderList','folder');RV.bindDrag('#songList','song')};
RV.renderBreadcrumb=function(){let items=[{id:null,name:'Biblioteca'},...RV.folderPath(RV.currentFolder)];if(RV.currentView==='inbox')items=[{id:null,name:'Biblioteca'},{id:'inbox',name:'Por organizar'}];$('#breadcrumb').innerHTML=items.map((x,i)=>`${i?'<span>›</span>':''}<button data-breadcrumb="${x.id??''}" data-inbox="${x.id==='inbox'}">${RV.esc(x.name)}</button>`).join('');$('#searchInput').placeholder=RV.currentView==='inbox'?'Buscar en Por organizar...':RV.currentFolder?`Buscar en ${RV.folderPath(RV.currentFolder).at(-1).name}...`:'Buscar en la biblioteca...'};
RV.populateDestinations=function(){$('#songDestination').innerHTML=['<option value="">Por organizar</option>',...RV.db.folders.map(f=>`<option value="${f.id}" ${f.id===RV.currentFolder?'selected':''}>${RV.esc(RV.folderPath(f.id).map(x=>x.name).join(' › '))}</option>`)].join('')};
RV.openFolder=function(id){RV.currentFolder=id||null;RV.currentView='library';$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view==='library'));$('#searchInput').value='';RV.render()};RV.setView=function(v){RV.currentView=v;if(v==='inbox')RV.currentFolder=null;$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===v));$('#searchInput').value='';RV.render()};
RV.bindDrag=function(selector,kind){const list=$(selector);if(!list||list.dataset.dragBound==='1')return;list.dataset.dragBound='1';let row=null,startY=0,timer=null,active=false;const finish=()=>{clearTimeout(timer);if(!row)return;if(active){row.classList.remove('dragging');RV.suppressOpenUntil=Date.now()+350;const ids=[...list.querySelectorAll(`.sortableRow[data-kind="${kind}"]`)].map(x=>x.dataset.id);ids.forEach((id,i)=>{const item=kind==='folder'?RV.db.folders.find(x=>x.id===id):RV.db.songs.find(x=>x.id===id);if(item)item.order=i});RV.save()}row=null;active=false};list.addEventListener('pointerdown',e=>{const handle=e.target.closest('.dragHandle');if(!handle)return;row=handle.closest('.sortableRow');startY=e.clientY;timer=setTimeout(()=>{active=true;row.classList.add('dragging');handle.setPointerCapture?.(e.pointerId)},170)});list.addEventListener('pointermove',e=>{if(!row)return;if(!active&&Math.abs(e.clientY-startY)>8){clearTimeout(timer);row=null;return}if(!active)return;e.preventDefault();const target=document.elementFromPoint(e.clientX,e.clientY)?.closest(`.sortableRow[data-kind="${kind}"]`);if(!target||target===row||target.parentElement!==list)return;const r=target.getBoundingClientRect();list.insertBefore(row,e.clientY<r.top+r.height/2?target:target.nextSibling)});list.addEventListener('pointerup',finish);list.addEventListener('pointercancel',finish)};
document.addEventListener('click',e=>{const id=e.target.closest('[data-id]')?.dataset.id;if(e.target.closest('.folderOpen'))RV.openFolder(id);else if(e.target.closest('.songOpen'))RV.playSong(id);else if(e.target.closest('.favoriteBtn'))RV.toggleFavorite(id);else if(e.target.closest('.moveSongBtn'))RV.moveSongPrompt(id);else if(e.target.closest('.deleteSongBtn'))RV.deleteSong(id);else if(e.target.closest('.renameFolderBtn'))RV.renameFolder(id);else if(e.target.closest('.deleteFolderBtn'))RV.deleteFolder(id);else if(e.target.matches('[data-breadcrumb]')){e.target.dataset.inbox==='true'?RV.setView('inbox'):RV.openFolder(e.target.dataset.breadcrumb||null)}});
$('#addFolderBtn').onclick=()=>{$('#folderName').value='';$('#folderDialog').showModal()};$('#folderForm').onsubmit=e=>{e.preventDefault();const n=$('#folderName').value.trim();if(!n)return;RV.db.folders.push({id:RV.uid(),name:n,parentId:RV.currentFolder,order:RV.db.folders.filter(f=>f.parentId===RV.currentFolder).length});RV.save();$('#folderDialog').close();RV.render()};$('#cancelFolderBtn').onclick=()=>$('#folderDialog').close();
$('#addSongBtn').onclick=()=>{$('#songUrl').value='';$('#songTitle').value='';$('#songArtist').value='';RV.populateDestinations();$('#songDialog').showModal()};$('#songForm').onsubmit=async e=>{e.preventDefault();const url=$('#songUrl').value.trim(),vid=RV.videoId(url);if(!vid)return alert('Ese enlace no parece ser un video válido de YouTube.');let title=$('#songTitle').value.trim(),artist=$('#songArtist').value.trim();if(!title){try{const r=await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent('https://www.youtube.com/watch?v='+vid)}&format=json`);if(r.ok){const m=await r.json();title=m.title;artist=m.author_name}}catch{}}const folderId=$('#songDestination').value||null;RV.db.songs.push({id:RV.uid(),videoId:vid,url,title:title||`Video de YouTube (${vid})`,artist,thumbnail:`https://i.ytimg.com/vi/${vid}/hqdefault.jpg`,folderId,order:RV.db.songs.filter(x=>x.folderId===folderId).length,favorite:false});RV.save();$('#songDialog').close();RV.render()};$('#cancelSongBtn').onclick=()=>$('#songDialog').close();
$('#searchInput').oninput=RV.render;$$('.tab').forEach(t=>t.onclick=()=>RV.setView(t.dataset.view));$('#settingsBtn').onclick=()=>{$('#libraryView').hidden=true;$('#settingsView').hidden=false};$('#backSettings').onclick=RV.render;$$('.skin').forEach(b=>b.onclick=()=>{RV.db.settings.skin=b.dataset.skin;RV.save();RV.applySkin()});$('#endMode').onchange=e=>{RV.db.settings.endMode=e.target.value;RV.save()};$('#resetBtn').onclick=()=>{if(confirm('¿Borrar todos los datos de prueba?')){RV.db=structuredClone(RV.seed);RV.save();RV.currentFolder=null;RV.render()}};
$('#nextBtn').onclick=RV.nextSong;$('#prevBtn').onclick=RV.prevSong;$('#playerToggle').onclick=()=>{const p=$('#playerBar');p.classList.toggle('collapsed');$('#playerToggle').textContent=p.classList.contains('collapsed')?'▴':'▾'};$('#playBtn').onclick=()=>{if(!RV.ytPlayer)return;RV.ytPlayer.getPlayerState()===1?RV.ytPlayer.pauseVideo():RV.ytPlayer.playVideo()};
$('#blockedOpenYoutube').onclick=()=>{const s=RV.queue[RV.queueIndex]||RV.db.songs.find(x=>x.id===RV.db.currentSong);if(s)window.open(s.url||`https://www.youtube.com/watch?v=${s.videoId}`,'_blank');$('#blockedDialog').close()};$('#blockedSkip').onclick=()=>{$('#blockedDialog').close();RV.nextSong()};$('#blockedDelete').onclick=()=>{const s=RV.queue[RV.queueIndex]||RV.db.songs.find(x=>x.id===RV.db.currentSong);$('#blockedDialog').close();if(s)RV.deleteSong(s.id)};
window.addEventListener('DOMContentLoaded',()=>{RV.applySkin();const p=new URLSearchParams(location.search),shared=p.get('url')||p.get('text');if(shared){$('#songUrl').value=shared;$('#songDialog').showModal()}RV.render();const yt=document.createElement('script');yt.src='https://www.youtube.com/iframe_api';document.head.appendChild(yt)});

function hideSplash() {
  const splash = document.getElementById('splash');
  const app = document.querySelector('.app');

  if (app) {
    app.classList.add('ready');
  }

  if (splash) {
    splash.style.opacity = '0';

    setTimeout(() => {
      splash.remove();
    }, 600);
  }
}

document.addEventListener('DOMContentLoaded', () => {
  setTimeout(hideSplash, 3500);
});

if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
