window.RV=window.RV||{};
RV.queue=[];
RV.queueIndex=-1;
RV.ytPlayer=null;
RV.ytReady=false;
RV.progressTimer=null;
RV.countedThisSession=false;
RV.activeSessionSongId=null;

RV.sortByOrder=function(items){return [...items].sort((a,b)=>(a.order??0)-(b.order??0))};
RV.getFolderPlaybackOrder=function(){const ordered=[];const visit=parentId=>{RV.sortByOrder(RV.db.folders.filter(f=>f.parentId===parentId)).forEach(folder=>{ordered.push(folder);visit(folder.id)})};visit(null);return ordered};
RV.getSongsInFolder=function(folderId){return RV.sortByOrder(RV.db.songs.filter(song=>song.folderId===folderId))};
RV.findNextPlayableFolder=function(currentFolderId){const folders=RV.getFolderPlaybackOrder();if(!folders.length)return null;const currentIndex=folders.findIndex(folder=>folder.id===currentFolderId),start=currentIndex>=0?currentIndex:folders.length-1;for(let step=1;step<=folders.length;step++){const candidate=folders[(start+step)%folders.length],songs=RV.getSongsInFolder(candidate.id);if(songs.length)return{folder:candidate,songs}}return null};
RV.buildQueue=function(song){RV.queue=song.folderId?RV.getSongsInFolder(song.folderId):RV.sortByOrder(RV.db.songs.filter(x=>!x.folderId));RV.queueIndex=RV.queue.findIndex(x=>x.id===song.id)};
RV.showPlayer=function(song){document.querySelector('#playerBar').hidden=false;document.querySelector('#playerThumb').src=song.thumbnail;document.querySelector('#playerTitle').textContent=song.title;document.querySelector('#playerMeta').textContent=song.artist||'Artista desconocido';RV.render?.()};
RV.beginSongSession=function(songId){RV.activeSessionSongId=songId;RV.countedThisSession=false};
RV.persistProgress=function(){if(!RV.ytReady||!RV.ytPlayer||!RV.db.currentSong)return;try{const state=RV.ytPlayer.getPlayerState(),position=Math.max(0,Number(RV.ytPlayer.getCurrentTime()||0)),duration=Math.max(0,Number(RV.ytPlayer.getDuration()||0));if(state===1||state===2){RV.playback={songId:RV.db.currentSong,position,updatedAt:Date.now()};RV.savePlayback()}if(!RV.countedThisSession&&duration>15&&position/duration>=.9){RV.incrementPlayCount(RV.db.currentSong);RV.countedThisSession=true;RV.updateTopFive?.()}}catch{}};
RV.startProgressTracking=function(){clearInterval(RV.progressTimer);RV.progressTimer=setInterval(RV.persistProgress,5000)};
RV.loadQueuedSong=function(song,options={}){if(!song)return;RV.db.currentSong=song.id;RV.save();RV.playback={songId:song.id,position:options.position||0,updatedAt:Date.now()};RV.savePlayback();RV.showPlayer(song);RV.beginSongSession(song.id);if(RV.ytReady){if(options.autoplay===false)RV.ytPlayer.cueVideoById({videoId:song.videoId,startSeconds:options.position||0});else RV.ytPlayer.loadVideoById({videoId:song.videoId,startSeconds:options.position||0})}};
RV.playSong=function(id){if(Date.now()<(RV.suppressOpenUntil||0))return;const song=RV.db.songs.find(x=>x.id===id);if(!song)return;RV.buildQueue(song);RV.loadQueuedSong(song);document.querySelector('#playerBar').classList.remove('collapsed');document.querySelector('#playerToggle').textContent='▾'};
RV.nextSong=function(){if(!RV.queue.length)return;RV.persistProgress();RV.queueIndex++;if(RV.queueIndex>=RV.queue.length){if(RV.db.settings.endMode==='repeat'){RV.queueIndex=0}else{const currentFolderId=RV.queue[0]?.folderId??null;if(currentFolderId===null){RV.queueIndex=0}else{const next=RV.findNextPlayableFolder(currentFolderId);if(next){RV.queue=next.songs;RV.queueIndex=0}else RV.queueIndex=0}}}RV.loadQueuedSong(RV.queue[RV.queueIndex])};
RV.prevSong=function(){if(!RV.queue.length)return;RV.persistProgress();RV.queueIndex=(RV.queueIndex-1+RV.queue.length)%RV.queue.length;RV.loadQueuedSong(RV.queue[RV.queueIndex])};
RV.handlePlayerError=function(code){const song=RV.queue[RV.queueIndex]||RV.db.songs.find(x=>x.id===RV.db.currentSong);if(!song)return;document.querySelector('#blockedSongName').textContent=song.title;document.querySelector('#blockedErrorCode').textContent=`Código de YouTube: ${code}`;document.querySelector('#blockedDialog').showModal()};
RV.toggleFullscreen=function(){const stage=document.querySelector('.videoStage');if(!stage)return;if(document.fullscreenElement)document.exitFullscreen?.();else stage.requestFullscreen?.().catch(()=>{})};
window.onYouTubeIframeAPIReady=()=>{RV.ytPlayer=new YT.Player('ytPlayer',{height:'360',width:'640',videoId:'',playerVars:{playsinline:1,controls:1,rel:0,fs:1},events:{onReady:()=>{RV.ytReady=true;const song=RV.db.songs.find(x=>x.id===RV.db.currentSong);if(song){RV.buildQueue(song);RV.showPlayer(song);const saved=RV.playback.songId===song.id?Math.max(0,Number(RV.playback.position||0)):0;RV.beginSongSession(song.id);RV.ytPlayer.cueVideoById({videoId:song.videoId,startSeconds:saved})}RV.startProgressTracking()},onStateChange:event=>{if(event.data===0){RV.persistProgress();RV.nextSong()}document.querySelector('#playBtn').textContent=event.data===1?'Ⅱ':'▶';document.body.classList.toggle('is-playing',event.data===1);RV.render?.()},onError:event=>RV.handlePlayerError(event.data)}})};
window.addEventListener('beforeunload',RV.persistProgress);
document.addEventListener('visibilitychange',()=>{if(document.hidden)RV.persistProgress()});
