window.RV=window.RV||{};
RV.VERSION='0.3.0';
RV.CREATED_AT='24 de julio de 2026';
RV.STORAGE_KEY='tma_db';
RV.PLAYBACK_KEY='riffvault_playback_v1';
RV.STATS_KEY='riffvault_stats_v1';
RV.SKINS={red:{accent:'#e32727',accent2:'#7a0c0c'},blue:{accent:'#2584ff',accent2:'#103d80'},gray:{accent:'#929292',accent2:'#444'}};
RV.seed={folders:[{id:'metal',name:'Metal',parentId:null,order:0},{id:'atmosphere',name:'Atmósfera',parentId:null,order:1},{id:'rock',name:'Rock',parentId:null,order:2},{id:'soundtracks',name:'Soundtracks',parentId:null,order:3},{id:'power',name:'Power Metal',parentId:'metal',order:0},{id:'metalcore',name:'Metalcore',parentId:'metal',order:1}],songs:[],settings:{skin:'red',endMode:'next'},currentFolder:null,currentSong:null};
RV.safeParse=function(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||'null');return value??fallback}catch{return fallback}};
RV.loadDB=function(){const raw=RV.safeParse(RV.STORAGE_KEY,null);const db=raw||structuredClone(RV.seed);db.folders=Array.isArray(db.folders)?db.folders:[];db.songs=Array.isArray(db.songs)?db.songs:[];db.settings={...RV.seed.settings,...(db.settings||{})};if(db.settings.skin==='grey')db.settings.skin='gray';return db};
RV.db=RV.loadDB();
RV.playback=RV.safeParse(RV.PLAYBACK_KEY,{songId:null,position:0,updatedAt:0});
RV.stats=RV.safeParse(RV.STATS_KEY,{plays:{}});
if(!RV.stats||typeof RV.stats!=='object')RV.stats={plays:{}};
if(!RV.stats.plays||typeof RV.stats.plays!=='object')RV.stats.plays={};
RV.save=function(){localStorage.setItem(RV.STORAGE_KEY,JSON.stringify(RV.db))};
RV.savePlayback=function(){localStorage.setItem(RV.PLAYBACK_KEY,JSON.stringify(RV.playback))};
RV.saveStats=function(){localStorage.setItem(RV.STATS_KEY,JSON.stringify(RV.stats))};
RV.getPlayCount=function(songId){return Number(RV.stats.plays[songId]||0)};
RV.incrementPlayCount=function(songId){RV.stats.plays[songId]=RV.getPlayCount(songId)+1;RV.saveStats()};
RV.uid=function(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)};
